# Generated by Django 5.2.5 on 2025-08-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaiapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivarity",
            name="description",
            field=models.TextField(default=" "),
        ),
    ]
