# Generated by Django 5.2.3 on 2025-07-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sid", models.IntegerField()),
                ("sname", models.CharField(max_length=100)),
                ("smarks", models.IntegerField()),
            ],
        ),
    ]
